In [19]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [66]:
dataset = pd.read_excel("/content/melb_data.xlsx")
dataset.head(10)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000,S,Biggin,2016-12-03,2.5,3067.0,...,1,1.0,202.0,NaN,NaN,Yarra,NaN,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000,S,Biggin,2016-02-04,2.5,3067.0,...,1,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000,SP,Biggin,2017-03-04,2.5,3067.0,...,2,0.0,134.0,150.0,1900.0,NaN,-37.8093,NaN,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000,PI,Biggin,2017-03-04,2.5,3067.0,...,2,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000,VB,Nelson,2016-06-04,2.5,3067.0,...,1,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0
5,Abbotsford,129 Charles St,2,h,941000,S,Jellis,2016-05-07,2.5,3067.0,...,1,NaN,181.0,NaN,NaN,Yarra,NaN,NaN,Northern Metropolitan,4019.0
6,Abbotsford,124 Yarra St,3,h,1876000,S,Nelson,2016-05-07,2.5,3067.0,...,2,NaN,245.0,210.0,1910.0,Yarra,-37.8024,144.9993,Northern Metropolitan,4019.0
7,Abbotsford,98 Charles St,2,h,1636000,S,Nelson,2016-10-08,2.5,3067.0,...,1,2.0,256.0,107.0,1890.0,Yarra,-37.8060,144.9954,Northern Metropolitan,4019.0
8,Abbotsford,6/241 Nicholson St,1,u,300000,S,Biggin,2016-10-08,2.5,NaN,...,1,NaN,0.0,NaN,NaN,Yarra,-37.8008,NaN,Northern Metropolitan,4019.0
9,Abbotsford,10 Valiant St,2,h,1097000,S,Biggin,2016-10-08,2.5,NaN,...,1,NaN,220.0,75.0,1900.0,Yarra,-37.8010,144.9989,Northern Metropolitan,4019.0

In [68]:
dataset.isnull().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode          138
hoal              118
Bathroom            0
Car               144
Landsize          121
BuildingArea     6450
YearBuilt        5375
CouncilArea      1487
Lattitude          36
Longtitude         71
Regionname         15
Propertycount      92
dtype: int64

In [69]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  int64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  datetime64[ns]
 8   Distance       13580 non-null  float64
 9   Postcode       13442 non-null  float64
 10  hoal           13462 non-null  float64
 11  Bathroom       13580 non-null  int64
 12  Car            13436 non-null  float64
 13  Landsize       13459 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12093 non-null  object
 17  Lattitude      13544 non-null  float64
 18  Longtitude     13509 non-null  float64
 19  Regionname     13565 non-null  object
 20  Propertycount  13488 non-null  float64
dtypes: datetime64[ns](1), float64(10), int64(3), object(7)
memory usage: 2.2+ MB

In [71]:
dataset.select_dtypes(include="float64").columns

Index(['Distance', 'Postcode', 'hoal', 'Car', 'Landsize', 'BuildingArea',
       'YearBuilt', 'Lattitude', 'Longtitude', 'Propertycount'],
      dtype='object')

In [72]:
from sklearn.impute import SimpleImputer

In [74]:
si = SimpleImputer(strategy="mean")
ar = si.fit_transform(dataset[['Distance','Postcode','hoal','Car','Landsize','BuildingArea','YearBuilt','Lattitude','Longtitude','Propertycount']])

In [75]:
pd.DataFrame(ar,columns = dataset.select_dtypes(include="float64").columns)

,Distance,Postcode,hoal,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
0,2.5,3067.0,2.000000,1.0,202.0,151.96765,1964.684217,-37.809286,144.998400,4019.0
1,2.5,3067.0,2.000000,0.0,156.0,79.00000,1900.000000,-37.807900,144.993400,4019.0
2,2.5,3067.0,3.000000,0.0,134.0,150.00000,1900.000000,-37.809300,144.995115,4019.0
3,2.5,3067.0,2.916134,1.0,94.0,151.96765,1964.684217,-37.796900,144.996900,4019.0
4,2.5,3067.0,3.000000,2.0,120.0,142.00000,2014.000000,-37.807200,144.994100,4019.0
...,...,...,...,...,...,...,...,...,...,...
13575,16.7,3150.0,4.000000,2.0,652.0,151.96765,1981.000000,-37.905620,145.167610,7392.0
13576,6.8,3016.0,3.000000,2.0,333.0,133.00000,1995.000000,-37.859270,144.879040,6380.0
13577,6.8,3016.0,3.000000,4.0,436.0,151.96765,1997.000000,-37.852740,144.887380,6380.0
13578,6.8,3016.0,4.000000,5.0,866.0,157.00000,1920.000000,-37.859080,144.892990,6380.0
13579,6.3,3013.0,4.000000,1.0,362.0,112.00000,1920.000000,-37.811880,144.884490,6543.0

In [76]:
new_dataset = pd.DataFrame(ar,columns = dataset.select_dtypes(include="float64").columns)

In [77]:
new_dataset.isnull().sum()

Distance         0
Postcode         0
hoal             0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
Lattitude        0
Longtitude       0
Propertycount    0
dtype: int64

In [78]:
new_dataset

,Distance,Postcode,hoal,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
0,2.5,3067.0,2.000000,1.0,202.0,151.96765,1964.684217,-37.809286,144.998400,4019.0
1,2.5,3067.0,2.000000,0.0,156.0,79.00000,1900.000000,-37.807900,144.993400,4019.0
2,2.5,3067.0,3.000000,0.0,134.0,150.00000,1900.000000,-37.809300,144.995115,4019.0
3,2.5,3067.0,2.916134,1.0,94.0,151.96765,1964.684217,-37.796900,144.996900,4019.0
4,2.5,3067.0,3.000000,2.0,120.0,142.00000,2014.000000,-37.807200,144.994100,4019.0
...,...,...,...,...,...,...,...,...,...,...
13575,16.7,3150.0,4.000000,2.0,652.0,151.96765,1981.000000,-37.905620,145.167610,7392.0
13576,6.8,3016.0,3.000000,2.0,333.0,133.00000,1995.000000,-37.859270,144.879040,6380.0
13577,6.8,3016.0,3.000000,4.0,436.0,151.96765,1997.000000,-37.852740,144.887380,6380.0
13578,6.8,3016.0,4.000000,5.0,866.0,157.00000,1920.000000,-37.859080,144.892990,6380.0
13579,6.3,3013.0,4.000000,1.0,362.0,112.00000,1920.000000,-37.811880,144.884490,6543.0

In [79]:
dataset["BuildingArea"].mean()

np.float64(151.96764988779805)