In [2]:
import pandas as pd

In [20]:
data = {"name": ["a","b","c","d","a","c"],"eng":[8,7,5,8,8,5],"hindi":[2,3,4,5,2,6]}

In [21]:
df = pd.DataFrame(data)
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
4    a    8      2
5    c    5      6

In [22]:
df.drop_duplicates()

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
5    c    5      6

In [23]:
df.drop_duplicates(inplace=True)

In [24]:
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
5    c    5      6

In [25]:
dataset = pd.read_excel("/content/melb_data.xlsx")

In [26]:
dataset.head(3)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000,S,Biggin,2016-12-03,2.5,3067.0,...,1,1.0,202.0,NaN,NaN,Yarra,NaN,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000,S,Biggin,2016-02-04,2.5,3067.0,...,1,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000,SP,Biggin,2017-03-04,2.5,3067.0,...,2,0.0,134.0,150.0,1900.0,NaN,-37.8093,NaN,Northern Metropolitan,4019.0

In [28]:
dataset.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
13575    False
13576    False
13577    False
13578    False
13579    False
Length: 13580, dtype: bool

In [29]:
dataset.shape

(13580, 21)

In [30]:
dataset.drop_duplicates(inplace=True)

In [31]:
dataset.shape

(13580, 21)