In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("/content/Social_Network_Ads.csv")

In [3]:
dataset.head(3)

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0

In [4]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [7]:
x = dataset.iloc[:,:-1]
y = dataset["Purchased"]

In [8]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [23]:
from imblearn.under_sampling import RandomUnderSampler

In [24]:
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler

In [25]:
ro = RandomOverSampler()
ro_x , ro_y = ro.fit_resample(x,y)

In [26]:
ro_y.value_counts()

Purchased
0    257
1    257
Name: count, dtype: int64

In [28]:
x_train1 , x_test1 , y_train1 , y_test1 = train_test_split(ro_x,ro_y,random_state=42,test_size=0.2)

In [29]:
lr1 = LogisticRegression()
lr1.fit(x_train1,y_train1)

LogisticRegression()

In [30]:
lr1.score(x_test1,y_test1)*100

86.40776699029125

In [31]:
lr1.predict([[19,19000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [10]:
!pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.12/dist-packages (0.14.0)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (2.0.2)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.16.2)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.5.2)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (3.6.0)

In [11]:
from imblearn.under_sampling import RandomUnderSampler

In [12]:
ru = RandomUnderSampler()
ru_x , ru_y = ru.fit_resample(x,y)

In [13]:
ru_y

225    0
104    0
88     0
298    0
170    0
      ..
393    1
395    1
396    1
397    1
399    1
Name: Purchased, Length: 286, dtype: int64

In [14]:
ru_y.value_counts()

Purchased
0    143
1    143
Name: count, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split

In [17]:
x_train , x_test , y_train , y_test = train_test_split(ru_x,ru_y,random_state=42,test_size=0.2)

In [19]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [20]:
lr.score(x_test,y_test)*100

77.58620689655173

In [21]:
lr.predict([[19,19000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])