In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_excel("/content/melb_data.xlsx")
dataset.head(3)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000,S,Biggin,2016-12-03,2.5,3067.0,...,1,1.0,202.0,NaN,NaN,Yarra,NaN,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000,S,Biggin,2016-02-04,2.5,3067.0,...,1,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000,SP,Biggin,2017-03-04,2.5,3067.0,...,2,0.0,134.0,150.0,1900.0,NaN,-37.8093,NaN,Northern Metropolitan,4019.0

In [ ]:
dataset.isnull().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode          138
hoal              118
Bathroom            0
Car               144
Landsize          121
BuildingArea     6450
YearBuilt        5375
CouncilArea      1487
Lattitude          36
Longtitude         71
Regionname         15
Propertycount      92
dtype: int64

In [ ]:
#dataset.fillna(10).head(10)

In [ ]:
#dataset.fillna(method="bfill",axis=1)

In [ ]:
#dataset.fillna(method="ffill",axis=1)

In [ ]:
dataset.fillna({"Method": dataset["Method"].mode()[0]}, inplace=True)

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  int64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  datetime64[ns]
 8   Distance       13580 non-null  float64
 9   Postcode       13442 non-null  float64
 10  hoal           13462 non-null  float64
 11  Bathroom       13580 non-null  int64
 12  Car            13436 non-null  float64
 13  Landsize       13459 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12093 non-null  object
 17  Lattitude      13544 non-null  float64
 18  Longtitude     13509 non-null  float64
 19  Regionname     13565 non-null  object
 20  Propertycount  13488 non-null  float64
dtypes: datetime64[ns](1), float64(10), int64(3), object(7)
memory usage: 2.2+ MB

In [ ]:
for col in dataset.select_dtypes(include="object").columns:
    dataset[col] = dataset[col].fillna(dataset[col].mode()[0])