In [17]:
import pandas as pd

In [23]:
dataset = pd.read_csv("/content/health_fitness_tracking_365days.csv")

In [24]:
dataset.head(3)

   user_id  age gender  ... stress_level  weight_kg        bmi
0        0   56      F  ...            2  73.496429  22.471978
1        0   56      F  ...            3  68.237867  22.569858
2        0   56      F  ...            4  81.687890  17.595609

[3 rows x 12 columns]

In [35]:
dataset.shape

(15457, 12)

In [31]:
input_data = dataset.iloc[:,:-1]
output_data = dataset["weight_kg"]

In [29]:
from sklearn.model_selection import train_test_split

In [32]:
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.2)

In [33]:
y_train

3492     57.347158
13691    67.768788
4479     63.965315
1840     67.006178
7360     98.890024
           ...
10543    74.015897
11428    79.297903
553      54.804557
13497    75.908347
6965     59.633337
Name: weight_kg, Length: 12365, dtype: float64

In [37]:
x_train.shape, y_train.shape

((12365, 11), (12365,))

In [38]:
x_test.shape, y_test.shape

((3092, 11), (3092,))